### ISSUE TITLE
[Bug] Pogreb nil value is erroneously counted as found key in Get method

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/hmap#31]
## Description
The method `hybrid.Get` at https://github.com/projectdiscovery/hmap/blob/2bfaa324a501f020450e5c36d8a4f5c0283f3e2f/store/disk/pogreb.go#L103 should return ErrNotFound if the item value is equal to nil
```go
if len(item) == 0 {
	return []byte{}, ErrNotFound
}
```

**Comment by ehsandeep** [comment]
Closed with https://github.com/projectdiscovery/hmap/pull/33
