### ISSUE TITLE
Memory leak in hmap memory

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/hmap#69]
The function `SetFinalizer` was not initialized correctly, leading to the GC never invoking it on an object going out of scope

**Comment by Bisstocuz** [comment]
@CodFrm said:
You mistakely returned wrong value [here](https://github.com/projectdiscovery/hmap/pull/66/commits/3f053f3cd18fb499bddb85779a12d3ce1a6b0605#diff-bdf0ddfb5c9ef5a689f1f22314f53f4724778508abb49f2fdc8154dcf24a75c7R201).

[This](https://github.com/projectdiscovery/hmap/pull/66/files#diff-bdf0ddfb5c9ef5a689f1f22314f53f4724778508abb49f2fdc8154dcf24a75c7R196) causes the wrapper to be collected by GC immediately.
